### ISSUE TITLE
Add "Welcome" topic

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/blog#13]
Add a welcome topic to the blog.

**Comment by raducoravu** [comment]
I added a small topic, maybe @StevenHiggs can take a look at it when he has the time.

**Comment by raducoravu** [comment]
https://oxygenxmlblog.netlify.com/welcome.html

**Comment by georgebina** [comment]
https://oxygenxmlblog.netlify.com/topics/welcome.html

**Comment by StevenHiggs** [comment]
I reviewed and improved the "welcome.html" file. I used the Edit Online link and committed on the master branch.

**Comment by raducoravu** [comment]
@StevenHiggs if in the commit message you specify the issue ID it will appear referenced in the topic.
Adding link to Steven's change:
https://github.com/oxygenxml/blog/commit/960f8e1bbfe770f5eaf51b7df179363b1218a226#diff-4cec3c28c48aacd5b906e438f6e12e85
